### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by dchun** [hdachev/heroku-buildpack-opencv#3]
I get the following error on heroku 18

```bash
remote:        Error: ERROR: failed to run: pkg-config "opencv >= 2.3.1" --cflags - Is OpenCV installed?
remote:            at /tmp/build_c1061747/node_modules/opencv/utils/find-opencv.js:29:21
remote:            at ChildProcess.exithandler (child_process.js:304:5)
remote:            at ChildProcess.emit (events.js:197:13)
remote:            at maybeClose (internal/child_process.js:984:16)
remote:            at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
remote:        gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
remote:        gyp ERR! configure error 
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_c1061747/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
remote:        gyp ERR! System Linux 4.4.0-1104-aws
remote:        gyp ERR! command "/tmp/build_c1061747/.heroku/node/bin/node" "/tmp/build_c1061747/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_c1061747/node_modules/opencv
remote:        gyp ERR! node -v v11.10.1
remote:        gyp ERR! node-gyp -v v3.8.0
remote:        gyp ERR! not ok 
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! opencv@7.0.0 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the opencv@7.0.0 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.w3UQP/_logs/2022-10-14T22_41_16_533Z-debug.log
remote: 
remote: -----> Build failed
```

Any ideas?

**Comment by hdachev** [comment]
Hey no idea, it's been ten years since i used this
Just looked into it now, back in the day I was running this on cedar, heroku-14
Maybe the prebuilt opencv doesn't run on their newer stuff
BTW heroku-18 is also deprecated
